#setwd("Desktop/DataCleaning_course/getdata-projectfiles-UCI HAR Dataset/UCI HAR Dataset")
#install.packages("reshape2","foreach")
library(reshape2)
library(foreach)
activityLabels<-read.table("activity_labels.txt")
labels<-read.table("features.txt")
x_test<-read.table("test/x_test.txt")
y_test<-read.table("test/y_test.txt")
subject_test<-read.table("test/subject_test.txt")
x_train<-read.table("train/x_train.txt")
y_train<-read.table("train/y_train.txt")
subject_train<-read.table("train/subject_train.txt")
all_data<-rbind(cbind(subject_test,y_test,x_test),cbind(subject_train,y_train,x_train))
colnames(all_data)<-c("subject","activity",as.character(labels[,2]))
selectData<-cbind(all_data[1:2],all_data[grep("ean",labels[,2],value=TRUE)],all_data[grep("std",labels[,2],value=TRUE)])
selectData_sort<-arrange(selectData,subject,activity)
subjectData<-split(selectData,selectData$subject)
finalData<-foreach(s=1:30, .combine=rbind) %:%
    foreach(a=1:6, .combine=rbind) %do% 
        as.data.frame(lapply(split(subjectData[[s]],subjectData[[s]]$activity)[[a]],mean))
nameActivity<-function(x) as.character(activityLabels[match(finalData[x,2],activityLabels[,1]),2])
for (observation in seq(length(finalData[,2])) ) finalData[observation,2]<-as.character(nameActivity(observation))
write.table(finalData, file="finalData.txt")
write.csv(finalData, file="finalData.csv")
